{
 "title": "Database Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "database",
    "query": {
     "query": "label_values(pg_database_size_bytes, datname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Распределение сессий по статусам ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (state) (pg_stat_activity_count{datname=\"data\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Размер самой большой таблицы",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_stat_user_tables_table_size_bytes{datname=\"data\"} / 1e6)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Скорость аллокации буферов",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_buffers_alloc_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Размер WAL файлов",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_wal_size_bytes / 1e9", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Размер индексов vs данных ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (datname) (pg_stat_user_tables_table_size_bytes{datname=\"data\"}) / 1e6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Размер индексов vs данных ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (datname) (pg_stat_user_tables_index_size_bytes{datname=\"data\"}) / 1e6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество таблиц",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (datname) (pg_stat_user_tables_n_live_tup{datname=\"data\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Reads per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_read{datname=~\"$database\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_blks_hit{datname=\"data\"}[5m])) \r\n/ (sum(rate(pg_stat_database_blks_hit{datname=\"data\"}[5m])) \r\n+ sum(rate(pg_stat_database_blks_read{datname=\"data\"}[5m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commits per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"data\"}[5m])\r\n+ rate(pg_stat_database_xact_rollback{datname=\"data\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname!~\"template.*\"} / 1e9",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname!~\"template.*|postgres\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}